name: info

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  info:
    runs-on: self-hosted

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: info
        run: |
          echo $USER
          echo $HOSTNAME
